[2025-02-21T09:40:06.774+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-02-21T09:40:06.825+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-01-29T00:00:00+00:00 [queued]>
[2025-02-21T09:40:06.838+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-02-21T09:40:07.069+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_task> on 2025-01-29 00:00:00+00:00
[2025-02-21T09:40:07.195+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'optum_etl_file_dag3', 'transform_task', 'scheduled__2025-01-29T00:00:00+00:00', '--job-id', '1001', '--raw', '--subdir', 'DAGS_FOLDER/optum_file_dag3.py', '--cfg-path', '/tmp/tmpuglrjhzb']
[2025-02-21T09:40:07.212+0000] {standard_task_runner.py:88} INFO - Job 1001: Subtask transform_task
[2025-02-21T09:40:07.172+0000] {standard_task_runner.py:60} INFO - Started process 5673 to run task
[2025-02-21T09:40:07.482+0000] {task_command.py:423} INFO - Running <TaskInstance: optum_etl_file_dag3.transform_task scheduled__2025-01-29T00:00:00+00:00 [running]> on host 491940227afd
[2025-02-21T09:40:07.805+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optum_etl_file_dag3' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-29T00:00:00+00:00'
[2025-02-21T09:40:07.815+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-21T09:40:07.856+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=optum_etl_file_dag3, task_id=transform_task, execution_date=20250129T000000, start_date=20250221T094006, end_date=20250221T094007
[2025-02-21T09:40:08.019+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-21T09:40:08.407+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
