[2025-02-21T09:13:01.540+0000] {processor.py:161} INFO - Started process (PID=20655) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:01.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:13:01.551+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:13:01.550+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:01.677+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:13:01.675+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:13:01.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:01.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.262 seconds
[2025-02-21T09:13:32.622+0000] {processor.py:161} INFO - Started process (PID=20715) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:32.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:13:32.631+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:13:32.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:32.698+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:13:32.696+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:13:32.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:13:32.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.158 seconds
[2025-02-21T09:14:03.888+0000] {processor.py:161} INFO - Started process (PID=20775) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:03.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:14:03.900+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:14:03.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:03.969+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:14:03.967+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:14:03.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:04.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.203 seconds
[2025-02-21T09:14:34.622+0000] {processor.py:161} INFO - Started process (PID=20834) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:34.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:14:34.630+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:14:34.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:34.711+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:14:34.709+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:14:34.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:14:34.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.191 seconds
[2025-02-21T09:15:05.087+0000] {processor.py:161} INFO - Started process (PID=20895) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:05.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:15:05.093+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:15:05.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:05.196+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:15:05.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:15:05.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:05.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.197 seconds
[2025-02-21T09:15:35.595+0000] {processor.py:161} INFO - Started process (PID=20956) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:35.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:15:35.607+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:15:35.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:35.736+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:15:35.732+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:15:35.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:15:35.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.250 seconds
[2025-02-21T09:16:06.416+0000] {processor.py:161} INFO - Started process (PID=21016) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:06.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:16:06.423+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:16:06.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:06.500+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:16:06.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:16:06.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:06.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.213 seconds
[2025-02-21T09:16:36.866+0000] {processor.py:161} INFO - Started process (PID=21077) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:36.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:16:36.872+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:16:36.871+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:36.928+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:16:36.926+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:16:36.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:16:37.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.166 seconds
[2025-02-21T09:17:07.486+0000] {processor.py:161} INFO - Started process (PID=21138) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:07.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:17:07.493+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:07.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:07.591+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:07.588+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 17
    fo=open("/tmp/sudoers_cleaned.txt","w")
                                          ^
TabError: inconsistent use of tabs and spaces in indentation
[2025-02-21T09:17:07.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:07.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.232 seconds
[2025-02-21T09:17:35.641+0000] {processor.py:161} INFO - Started process (PID=21193) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:35.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:17:35.652+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:35.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:35.741+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:35.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 44
    schedule_interval='"@daily"  # Runs daily
                                            ^
SyntaxError: EOL while scanning string literal
[2025-02-21T09:17:35.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:35.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.193 seconds
[2025-02-21T09:17:44.806+0000] {processor.py:161} INFO - Started process (PID=21214) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:44.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:17:44.816+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:44.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:44.933+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:44.928+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/optum_file_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/optum_file_dag.py", line 45
    catchup=True
    ^
SyntaxError: invalid syntax
[2025-02-21T09:17:44.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:44.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.187 seconds
[2025-02-21T09:17:59.124+0000] {processor.py:161} INFO - Started process (PID=21247) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:59.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:17:59.130+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:59.275+0000] {processor.py:840} INFO - DAG(s) 'optum_file_dag' retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:17:59.746+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.744+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:optum_file_dag
[2025-02-21T09:17:59.794+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.793+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:optum_file_dag
[2025-02-21T09:17:59.833+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.832+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:optum_file_dag
[2025-02-21T09:17:59.837+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.836+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-21T09:17:59.879+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.879+0000] {dag.py:3058} INFO - Creating ORM DAG for optum_file_dag
[2025-02-21T09:17:59.915+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:17:59.914+0000] {dag.py:3823} INFO - Setting next_dagrun for optum_file_dag to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-02-21T09:17:59.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.868 seconds
[2025-02-21T09:18:00.645+0000] {processor.py:161} INFO - Started process (PID=21253) to work on /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:18:00.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/optum_file_dag.py for tasks to queue
[2025-02-21T09:18:00.652+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:18:00.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:18:00.767+0000] {processor.py:840} INFO - DAG(s) 'optum_file_dag' retrieved from /opt/airflow/dags/optum_file_dag.py
[2025-02-21T09:18:00.809+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:18:00.808+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-21T09:18:00.880+0000] {logging_mixin.py:188} INFO - [2025-02-21T09:18:00.879+0000] {dag.py:3823} INFO - Setting next_dagrun for optum_file_dag to 2025-01-01 00:00:00+00:00, run_after=2025-01-02 00:00:00+00:00
[2025-02-21T09:18:00.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/optum_file_dag.py took 0.327 seconds
